### ISSUE TITLE
port to Linux

### ISSUE THREAD

**Issue by jf3110** [SChernykh/RandomX_OpenCL#2]
I just finished porting/compiling on Linux. How can I contribute the changes? A Vega 64 managed to achieve 1052 H/s with about 5% over-clocking from stock clocks. How about porting to Polaris?

**Comment by SChernykh** [comment]
Do a pull request then. Which Linux and driver version did you use? I'm going to work on code for Polaris in August.

**Comment by jf3110** [comment]
The driver was AMDGPU-PRO 19.20 on Gentoo, but I'll start with
creating cmake files for compatibility.

Work on Polaris is great news.

Tried also with ROCm 2.6, but gcn assembler has different meta-data.

2019-07-30 23:48 GMT+02:00, SChernykh <notifications@github.com>:

**Comment by SChernykh** [comment]
I've added makefile and instructions for Linux, tested on Ubuntu 18.04.
